# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CallDownAndInPrice <- function(nInt_ = 100L, Strike_ = 50, Spot_ = 45, Vol_ = 0.25, r_ = 0.04, Expiry_ = 0.5, barrier_ = 55) {
    .Call(`_Down_and_In_OptionPricer_CallDownAndInPrice`, nInt_, Strike_, Spot_, Vol_, r_, Expiry_, barrier_)
}

PutDownAndInPrice <- function(nInt_ = 100L, Strike_ = 50, Spot_ = 45, Vol_ = 0.25, r_ = 0.04, Expiry_ = 0.5, barrier_ = 55) {
    .Call(`_Down_and_In_OptionPricer_PutDownAndInPrice`, nInt_, Strike_, Spot_, Vol_, r_, Expiry_, barrier_)
}

rcpp_hello_world <- function() {
    .Call(`_Down_and_In_OptionPricer_rcpp_hello_world`)
}

